#!/usr/bin/python3
from support import *
v=Verifier(256,64,4)
initialSetting=v.getInitialSettingPacket()
print(initialSetting)
p=Prover(b'FLAG',b'KEY')
p.createFullKnowledge(initialSetting)
cur_res=p.createGraphSetPacketAndHash(initialSetting)
print ('Created Graph packet')
if cur_res==None:
    exit()
(graphSetPacket,signature)=cur_res
print(v.updateZKnGraph(graphSetPacket,signature))
print ('Updated full knowledge')
prV=ZKNProtocolVerifier(v)
configurationPacket=prV.createProofConfigurationPacket()
print(configurationPacket)
print ('Created configuration packet')
p.initializeProofHelper(configurationPacket)
print('Initialized proof helper')
p.createProofs()
print('Created proofs')
print (p.proofs_for_one_round)
commitment=p.createCommitmentPacket()
print('Created commitment')
#print (commitment)
prV.saveCommitment(commitment)
challenge=prV.createChallenge()
print(challenge)
reveal=p.createRevealPacket(challenge)
#print(reveal)
print (prV.checkProof(reveal))